name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
env:
  VITE_API_TEST: ${{secrets.VITE_API_TEST}},
  VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install, build 🔧
        run: |
          npm install
          npm run build
          cp ./dist/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
